version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Instalar gh-pages
          command: npm install gh-pages --save-dev
      - run:
          name: Configurar Git y desplegar
          command: |
            git config --global user.email "deploy@circleci.com"
            git config --global user.name "CircleCI Deploy"
            npx gh-pages -d . --repo=https://${GH_TOKEN}@github.com/nayes28/lab-circleci-html.git

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy
